hyp_params: !!python/object:argparse.Namespace
  batch_size: 32
  chk: 3
  cnn_model: vgg16
  criterion: !!python/object:torch.nn.modules.loss.BCEWithLogitsLoss
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: !!python/object/apply:collections.OrderedDict
    - - - weight
        - null
      - - pos_weight
        - null
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: !!python/object/apply:collections.OrderedDict
    - []
    _parameters: !!python/object/apply:collections.OrderedDict
    - []
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    reduction: mean
    training: true
  data_path: /001/usuarios/isaac.bribiesca/
  dataset: mmimdb
  gpus: 1
  gradient_clip_val: 0.57835
  hidden_size: 512
  image_feature_size: 4096
  log_interval: 100
  lr: 4.4e-05
  max_epochs: 100
  mlp_dropout: 0.0445
  model: GMU
  name: GMU
  no_cuda: false
  optim: Adam
  output_dim: 23
  search: false
  seed: 1111
  test: false
  text_embedding_size: 300
  use_cuda: true
  when: 3
trial: null
