hyp_params: !!python/object:argparse.Namespace
  batch_size: 128
  chk: 3
  cnn_model: vgg16
  data_path: /001/usuarios/isaac.bribiesca/
  dataset: mmimdb
  gamma: 0.49522546968628184
  gpus: 1
  gradient_clip_val: 0.43852630243143503
  hidden_size: 512
  image_feature_size: 4096
  label_weights: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYDgAAADkzOTU0OTk4MzczNzEycQJYBgAAAGN1ZGE6MHEDSxdOdHEEUS6AAl1xAFgOAAAA
      OTM5NTQ5OTgzNzM3MTJxAWEuFwAAAAAAAADNHtM79IyPPMzyMz3kP0E98xayPe+gyT0/ZTQ+WTM2
      Pq+6mT68epo+XlyfPsderT4JvvQ++Cs0Pzl/PD+WIH0/epiRP6Bsqj/fTuc/eokjQHy2S0B6SrlA
      6kczQQ==
  - 0
  - !!python/tuple
    - 23
  - !!python/tuple
    - 1
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  log_interval: 100
  lr: 7.475444e-06
  max_epochs: 200
  mlp_dropout: 0.17784427689642585
  model: MLPGenreClassifier
  name: MLPGenreClassifier
  no_cuda: false
  optim: Adam
  output_dim: 23
  search: false
  seed: 1111
  test: false
  text_embedding_size: 300
  use_cuda: false
  when: 7
trial: null
